### ISSUE TITLE
Fix syntax error in f-string formatting in simulate.py

### ISSUE THREAD

**Issue by imertz** [vtripolitakis/task_executor#1]
### Issue Description
A syntax error was discovered in `simulate.py` where an f-string was incorrectly split across multiple lines, causing the script to fail with a `SyntaxError: unterminated string literal`.

**File:** `simulate.py`  
**Line:** 186  
**Error Message:**
```
File "/home/imertz/coding/python/task_executor/simulate.py", line 186
    print(f"Running scenario: {
          ^
SyntaxError: unterminated string literal (detected at line 186)
```

**Comment by vtripolitakis** [comment]
Thanks. Merged.
